### ISSUE TITLE
Fails on d3-geo-projection

### ISSUE THREAD

**Issue by mattcg** [jfhbrook/browserify-cdn#96]
Here's the error output from wzrd.in for [a request](https://wzrd.in/standalone/d3-geo-projection@latest) for this module:

```
---FLAGRANT SYSTEM ERROR---

(logs uuid: 12e40a70-bf93-11e4-b49a-c5f4df644012 )

Error: "browserify exited with code 1"

code: 1
stderr: SyntaxError: Line 4: Unexpected token . while parsing /tmp/d3-geo-projection115128-2995-108xrhq/node_modules/d3-geo-projection/index.js while parsing file: /tmp/d3-geo-projection115128-2995-108xrhq/node_modules/d3-geo-projection/index.js
    at Stream.end (/home/admin/browserify-cdn/node_modules/browserify/node_modules/insert-module-globals/index.js:73:21)
    at _end (/home/admin/browserify-cdn/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/admin/browserify-cdn/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:74:5)
    at Transform.onend (/home/admin/browserify-cdn/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:180:16)
    at Transform.EventEmitter.emit (events.js:117:20)
    at /home/admin/browserify-cdn/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:415:13)

dirPath: /tmp/d3-geo-projection115128-2995-108xrhq

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/jesusabdullah/browserify-cdn/issues

Include the ENTIRETY of the contents of this message, and he can
try to help you out.

Have a nice day!
```

**Comment by jfhbrook** [comment]
The error seems to indicate that `d3-geo-projection/index.js` contains invalid javascript...

**Comment by mattcg** [comment]
That's strange, because there are no syntax errors in the file.

```
$ jshint d3-geo-projection/index.js 
d3-geo-projection/index.js: line 4, col 30, The Function constructor is a form of eval.

1 error
```

**Comment by mattcg** [comment]
Sorry, this seems to be a problem with browserify itself. I've filed substack/node-browserify/issues/1142.
